
[general]

	[general.settings]
		my_setting = true
		show_container_inventory_when_opened = false
		show_container_inventory_on_click = false
		stash_message = true
		inq_detector = true
		change_stash_open = 0
		hide_falling_blocks = false
		replace_ah_message = true
		party_invite_message_editor = true
		change_stash_action = 0

